# Generated by Django 5.1 on 2024-08-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(choices=[('São Miguel', 'São Miguel'), ('Pau dos Ferros', 'Pau dos Ferros')], max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('curso', models.CharField(choices=[('Informática', 'Informática'), ('Alimentos', 'Alimentos'), ('Apicultura', 'Apicultura')], max_length=200)),
            ],
        ),
    ]
